### ISSUE TITLE
kivymd in the path fails to start application

### ISSUE THREAD

**Issue by cederom** [kivymd/KitchenSink#1]
### Description of the Bug

* KitchenSink (master) fails to run when there is a `kivymd` in the path :-(
* At first I have cloned KitchenSink repo to `kivymd-KitchenSink.git` and that caused application crash on start.
* The same situation is when code is in `~/kivymd/KitchenSink.git`.
* Moving to a location with no `kivymd` anywhere in the path fixed the issue.
* That should be no problem where I run the app from? :-)
* I hope this is not the case for all KivyMD apps??

### Code and Logs

```
(venv3.9embedded) python main.py
[INFO   ] [Logger      ] Record log in /XXX/.kivy/logs/kivy_22-08-15_2.txt
[INFO   ] [Kivy        ] v2.1.0
[INFO   ] [Kivy        ] Installed at "/XXX/.local/venv3.9embedded/lib/python3.9/site-packages/kivy/__init__.py"
[INFO   ] [Python      ] v3.9.13 (main, May 19 2022, 01:16:32)
[Clang 11.0.1 (git@github.com:llvm/llvm-project.git llvmorg-11.0.1-0-g43ff75f2c
[INFO   ] [Python      ] Interpreter at "/XXX/.local/venv3.9embedded/bin/python"
[INFO   ] [Logger      ] Purge log fired. Processing...
[INFO   ] [Logger      ] Purge finished!
[INFO   ] [Factory     ] 189 symbols loaded
[INFO   ] [Image       ] Providers: img_tex, img_dds, img_sdl2, img_pil (img_ffpyplayer ignored)
[INFO   ] [Window      ] Provider: sdl2
[INFO   ] [GL          ] Using the "OpenGL" graphics system
[INFO   ] [GL          ] Backend used <sdl2>
[INFO   ] [GL          ] OpenGL version <b'4.6 (Compatibility Profile) Mesa 21.3.8'>
[INFO   ] [GL          ] OpenGL vendor <b'AMD'>
[INFO   ] [GL          ] OpenGL renderer <b'AMD Radeon RX 580 Series (POLARIS10, DRM 3.35.0, 13.1-STABLE, LLVM 13.0.1)'>
[INFO   ] [GL          ] OpenGL parsed version: 4, 6
[INFO   ] [GL          ] Shading version <b'4.60'>
[INFO   ] [GL          ] Texture max size <16384>
[INFO   ] [GL          ] Texture max units <32>
[INFO   ] [Window      ] auto add sdl2 input provider
[INFO   ] [Window      ] virtual keyboard not allowed, single mode, not docked
[INFO   ] [KivyMD      ] 1.0.2, git-38fe356, 2022-08-11 (installed at "/XXX/.local/venv3.9embedded/lib/python3.9/site-packages/kivymd/__init__.py")
[INFO   ] [Text        ] Provider: sdl2(['text_pango'] ignored)
[INFO   ] [GL          ] NPOT texture support is available
[CRITICAL] [KivyMD      ] Do not use the word 'kivymd' in the name of the directory from where you download KV files
[CRITICAL] [KivyMD      ] Do not use the word 'kivymd' in the name of the directory from where you download KV files
[CRITICAL] [KivyMD      ] Do not use the word 'kivymd' in the name of the directory from where you download KV files
[CRITICAL] [KivyMD      ] Do not use the word 'kivymd' in the name of the directory from where you download KV files
[CRITICAL] [KivyMD      ] Do not use the word 'kivymd' in the name of the directory from where you download KV files
[CRITICAL] [KivyMD      ] Do not use the word 'kivymd' in the name of the directory from where you download KV files
 Traceback (most recent call last):
   File "kivy/properties.pyx", line 961, in kivy.properties.ObservableDict.__getattr__
 KeyError: 'menu_list'

 During handling of the above exception, another exception occurred:

 Traceback (most recent call last):
   File "/XXX/kivymd-KitchenSink.git/main.py", line 34, in <module>
     KitchenSink().run()
   File "/XXX/.local/venv3.9embedded/lib/python3.9/site-packages/kivy/app.py", line 954, in run
     self._run_prepare()
   File "/XXX/.local/venv3.9embedded/lib/python3.9/site-packages/kivy/app.py", line 924, in _run_prepare
     root = self.build()
   File "/XXX/kivymd-KitchenSink.git/main.py", line 30, in build
     self.manager_screen.add_widget(self.manager_screen.create_screen("menu"))
   File "/XXX/.local/venv3.9embedded/lib/python3.9/site-packages/kivy/uix/screenmanager.py", line 1001, in add_widget
     self.current = widget.name
   File "kivy/properties.pyx", line 520, in kivy.properties.Property.__set__
   File "kivy/properties.pyx", line 567, in kivy.properties.Property.set
   File "kivy/properties.pyx", line 606, in kivy.properties.Property._dispatch
   File "kivy/_event.pyx", line 1307, in kivy._event.EventObservers.dispatch
   File "kivy/_event.pyx", line 1213, in kivy._event.EventObservers._dispatch
   File "/XXX/kivymd-KitchenSink.git/View/ManagerScreen/manager_screen.py", line 26, in on_current
     super().on_current(*args)
   File "/XXX/.local/venv3.9embedded/lib/python3.9/site-packages/kivy/uix/screenmanager.py", line 1069, in on_current
     screen.dispatch('on_enter')
   File "kivy/_event.pyx", line 731, in kivy._event.EventDispatcher.dispatch
   File "/XXX/kivymd-KitchenSink.git/View/MenuScreen/menu_screen.py", line 10, in on_enter
     if not self.ids.menu_list.data:
   File "kivy/properties.pyx", line 964, in kivy.properties.ObservableDict.__getattr__
 AttributeError: 'super' object has no attribute '__getattr__'

```

### Screenshots

No screenshot available. Application fail to start.

### Versions

* OS: FreeBSD 13-STABLE.
* Python: 3.9.13 (in Virtual Env).
* Kivy: 2.1.0 (release).
* KivyMD: master (4e3b7565263a81e4d19a5a283aad134218c0173a).

**Comment by HeaTTheatR** [comment]
@cederom 
`[CRITICAL] [KivyMD      ] Do not use the word 'kivymd' in the name of the directory from where you download KV files`
